pipeline:
  quality_threshold: 0.85
  max_retries: 3
  min_improvement: 0.01
  language_tool_threshold: 0.02
  bleu_threshold: 35.0

llm:
  profile: "default"  # or "local"
  model: "gpt-4.1-mini"
  temperature: 0.7

translator:
  model: "gpt-4"
  temperature: 0.7
  prompt: "Translate the following text to {target_lang}:\n{text}\n翻訳結果のみを返してください。"

proofreader:
  model: "gpt-4o"
  style: "general"
  temperature: 0.0
  prompt: "Proofread the following text. Fix grammar, style, and readability issues in {style} style. 文の意味を変えないこと。未知の用語はそのまま残すこと。結果だけを出力してください。"

whisper:
  model: "large"
  language:

output_dir: "output"
temp_dir: "temp"
log_dir: "logs"
